version: '3.8'

services:
  pg:
    container_name: blog-backend-pg
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    container_name: blog-backend-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '5050:80'
  devmailer:
    container_name: blog-backend-devmailer
    image: maildev/maildev
    restart: always
    ports:
      - '1080:1080'
      - '1025:1025'

volumes:
  db:
    driver: local
